// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// logit
Rcpp::NumericVector logit(Rcpp::NumericVector x);
RcppExport SEXP qwraps2_logit(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(logit(x));
    return __result;
END_RCPP
}
// invlogit
Rcpp::NumericVector invlogit(Rcpp::NumericVector x);
RcppExport SEXP qwraps2_invlogit(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(invlogit(x));
    return __result;
END_RCPP
}
