# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title logit and inverse logit functions
#' 
#' @description transform \code{x} either via the logit, or inverse logit.
#'
#' @details Why are these functions are not part of base R?  I don't have the
#' answer to that question.  So here are functions for easy of use.
#'
#' @param x a numeric vector
#' @export
#' @rdname logit
logit <- function(x) {
    .Call('qwraps2_logit', PACKAGE = 'qwraps2', x)
}

#' @export
#' @rdname logit
invlogit <- function(x) {
    .Call('qwraps2_invlogit', PACKAGE = 'qwraps2', x)
}

